<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SmartHome system')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/glyphicon.min.css'))
                ->prependStylesheet($this->basePath('css/signin.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/date.format.js'))
        ?>
        
    </head>
    <body>

        <nav class="navbar navbar-expand-md bg-primary navbar-dark mb-4 col-8 offset-2">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">SmartHOME - Domů</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <?php /*
            
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link font-weight-bold" href="<?= $this->url('download') ?>">Download</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link font-weight-bold" href="<?= $this->url('about-nana') ?>">About Nana </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link font-weight-bold" href="<?= $this->url('todo') ?>">Todo </a>
                    </li>
                </ul>

            </div>
             
             */
            
            ?>
            
        </nav>

        <div class="container col-8">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2009 - <?= date('Y') ?> by Martin Mikač - <strong>martin.mikac(at)gmail.com </strong>  </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
