<div class="jumbotron">
    <h1>Vítejte na <span class="m-blue">SmartHome system</span></h1>

    <p>
        Systém pro zobrazování zpráv a údajů získaných ze senzorů!
    </p>
</div>

<div class="card mt-5 ">

    <div class="card-header bg-primary ">
        <h4 class="card-title text-light">Základní přehled - údajů</h4>
    </div>

    <div class="card-body pt-3">

        <div class="row">
            
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Senzor vlhkosti : balkón 1.p</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            Aktuální stav:
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Searchable by web frontend</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            All devices are searchable by web frontend
                        </p>
                    </div>
                </div>
            </div>

        </div>
        
        
        <?php
        
        /*
        
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Asynchronous DNS reverse resolver</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">L2 network topology</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            L2 network topology discovery based on FDB from Bridge MIB
                        </p>
                    </div>
                </div>
            </div>


                

        </div>
                  */
        
        ?>
    </div>

</div>




